# Generated by Django 4.0.3 on 2022-04-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinoturistico',
            fields=[
                ('iddestino', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id destino')),
                ('nomdestino', models.CharField(max_length=30, verbose_name='Destino Turistico')),
                ('preciodestino', models.IntegerField(verbose_name='Precio destino')),
                ('multimedia', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('direcllegada', models.CharField(max_length=50, verbose_name='Direccion llegada')),
                ('descripciondes', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('horario_viaje', models.DateTimeField(verbose_name='Horario')),
            ],
        ),
    ]
