# Generated by Django 4.0.3 on 2022-04-10 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombrecliente', models.CharField(max_length=20, null=True)),
                ('apellidoscliente', models.CharField(max_length=40, null=True)),
                ('edadcliente', models.IntegerField(null=True)),
                ('direccioncliente', models.CharField(max_length=30, null=True)),
                ('celularcliente', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Cliente',
                'ordering': ['idcliente'],
            },
        ),
        migrations.CreateModel(
            name='Destinoturistico',
            fields=[
                ('iddestino', models.AutoField(primary_key=True, serialize=False)),
                ('nomdestino', models.CharField(max_length=30, null=True, verbose_name='Destino Turistico')),
                ('preciodestino', models.IntegerField(null=True, verbose_name='Precio destino')),
                ('multimedia', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('direcllegada', models.CharField(max_length=50, null=True, verbose_name='Direccion llegada')),
                ('descripciondes', models.CharField(max_length=50, null=True, verbose_name='Descripcion')),
                ('horario_viaje', models.DateTimeField(null=True, verbose_name='Horario')),
            ],
            options={
                'db_table': 'destinoTuristico',
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('idtransporte', models.IntegerField(primary_key=True, serialize=False)),
                ('tipotransporte', models.CharField(max_length=20)),
                ('preciotransporte', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('descripciontransporte', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Transportes',
                'ordering': ['idtransporte'],
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('idboleto', models.IntegerField(primary_key=True, serialize=False)),
                ('fechaviaje', models.DateTimeField()),
                ('fechaemision', models.DateTimeField()),
                ('tipopago', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('preciototal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('idcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyturismo.cliente')),
                ('iddestino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyturismo.destinoturistico')),
                ('idtransporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyturismo.transporte')),
            ],
            options={
                'db_table': 'Boleto',
                'ordering': ['idboleto'],
            },
        ),
    ]
