# Generated by Django 4.0.3 on 2022-04-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyturismo', '0002_remove_destinoturistico_horario_viaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinoturistico',
            name='descripciondes',
        ),
        migrations.RemoveField(
            model_name='destinoturistico',
            name='direcllegada',
        ),
        migrations.RemoveField(
            model_name='destinoturistico',
            name='multimedia',
        ),
        migrations.RemoveField(
            model_name='destinoturistico',
            name='nomdestino',
        ),
        migrations.RemoveField(
            model_name='destinoturistico',
            name='preciodestino',
        ),
        migrations.AlterField(
            model_name='destinoturistico',
            name='iddestino',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
