# Generated by Django 4.0.3 on 2022-04-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyturismo', '0003_remove_destinoturistico_descripciondes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinoturistico',
            name='descripciondes',
            field=models.CharField(max_length=50, null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='destinoturistico',
            name='direcllegada',
            field=models.CharField(max_length=50, null=True, verbose_name='Direccion llegada'),
        ),
        migrations.AddField(
            model_name='destinoturistico',
            name='horario_viaje',
            field=models.DateTimeField(null=True, verbose_name='Horario'),
        ),
        migrations.AddField(
            model_name='destinoturistico',
            name='multimedia',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='destinoturistico',
            name='nomdestino',
            field=models.CharField(max_length=30, null=True, verbose_name='Destino Turistico'),
        ),
        migrations.AddField(
            model_name='destinoturistico',
            name='preciodestino',
            field=models.IntegerField(null=True, verbose_name='Precio destino'),
        ),
        migrations.AlterField(
            model_name='destinoturistico',
            name='iddestino',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id destino'),
        ),
    ]
