# Generated by Django 4.0.3 on 2022-04-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyturismo', '0004_destinoturistico_descripciondes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinoturistico',
            name='descripciondes',
        ),
        migrations.RemoveField(
            model_name='destinoturistico',
            name='direcllegada',
        ),
        migrations.RemoveField(
            model_name='destinoturistico',
            name='horario_viaje',
        ),
        migrations.RemoveField(
            model_name='destinoturistico',
            name='multimedia',
        ),
        migrations.RemoveField(
            model_name='destinoturistico',
            name='preciodestino',
        ),
        migrations.AlterField(
            model_name='destinoturistico',
            name='iddestino',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
