# Generated by Django 4.0.3 on 2022-04-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyturismo', '0006_destinoturistico_descripciondes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinoturistico',
            name='iddestino',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
