# Generated by Django 4.0.3 on 2022-04-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyturismo', '0007_alter_destinoturistico_iddestino'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('ci', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('ap_pa', models.CharField(max_length=20)),
                ('ap_ma', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=30)),
                ('celular', models.IntegerField()),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.AlterModelTable(
            name='destinoturistico',
            table='destinoTuristico',
        ),
    ]
